image: ondrejsika/ci

stages:
  - build
  - deploy dev
  - validate dev
  - deploy prod
  - validate prod

variables:
  DOMAIN: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN
  IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA

build:
  stage: build
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $IMAGE .
    - docker push $IMAGE

.deploy: &deploy
  script:
    - helm repo add ondrejsika https://helm.oxs.cz
    - helm upgrade --install main ondrejsika/one-image --set image=$IMAGE --set host=$DOMAIN
    - kubectl rollout status deploy/main

.validate: &validate
  script:
    - curl https://$DOMAIN

.dev: &dev
  environment:
    name: dev/$CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN

.prod: &prod
  environment:
    name: prod/master
    url: https://$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN

deploy dev:
  <<: *deploy
  <<: *dev
  stage: deploy dev

validate dev:
  <<: *validate
  <<: *dev
  stage: validate dev

deploy prod:
  <<: *deploy
  <<: *prod
  stage: deploy prod

validate prod:
  <<: *validate
  <<: *dev
  stage: validate prod
