image: ondrejsika/ci

stages:
  - build
  - deploy dev
  - validate dev
  - deploy prod
  - validate prod

variables:
  DOMAIN: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN

build:
  stage: build
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

deploy dev:
  stage: deploy dev
  script:
    - helm repo add ondrejsika https://helm.oxs.cz
    - helm upgrade --install main ondrejsika/one-image --set image=$CI_REGISTRY_IMAGE --set host=$DOMAIN
  environment:
    name: dev/$CI_COMMIT_REF_SLUG
    url: https://$DOMAIN
